name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Snyk Vulnerability Scan
      uses: snyk/actions@0.3.0
      env:
          SNYK_TOKEN: $f853b6e4-d988-46f6-aa3f-174b5346b670
      with:
        command: monitor
        args: --all-projects
